### PR TITLE
fix(go): fix the build error of generated code for empty resource type

### LINKED ISSUE #929: If an exported interface uses an exported resource type, the generated code won't compile
```wit
package foo:bar;

interface f {
    resource fd;
}

interface utils {
    use f.{fd};
    my-func: func() -> own<fd>;
}

world test {
    import f;
    export f;
    export utils;
}
```

The generated TinyGo code failed to compile for this WIT file. Notice that the `fd` from `utils` is the exported `f.{fd}` type.

### PR DESCRIPTION
**Pull request by Mossaka**
If a resource is exported and that resource doesn't have a constructor, the generated Go code would fail. This PR fixes this issue by allowing the generator to generate Go types and interfaces if there are exported resources. 

Closes #929

### CODE REVIEW

**Comment by Mossaka** [comment]
Ahh it seems like the added codegen test cases also failed the rust generator, could you please take a look 👀? @alexcrichton

**Comment by alexcrichton** [comment]
Want to exclude this test in Rust for now? I can come and fix it after this lands (looks benign and related to how things are tested)

**Comment by Mossaka** [comment]
Skipped these tests for the rust bindgen

**Comment by FrankReh** [comment]
May I ask the title of this PR be changed to reflect what the fix is? That would make it more consistent with other PRs in this repo. And adding Go or Golang to it would make it even more precise.

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
