### PR TITLE
Add support for MoonBit

### PR DESCRIPTION
**Pull request by peter-jerry-ye**
Hi,

This PR implements the support for MoonBit, a programming language that compiles to WebAssembly.

There are still a few things to be polished before it's ready, but most features have been implemented.

cc @bobzhang

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I don't know much about MoonBit myself so I won't be able to review those parts, much, but I'll review the CI parts and integration when this is ready

**Comment by peter-jerry-ye** [comment]
Sorry, I need to rethink of the generated project layout with some users' feedback.

**Review by alexcrichton — APPROVED** [review]
The integration bits all look good to me here, thanks! When you feel that the MoonBit side of things is ready let me know

**Comment by alexcrichton** [comment]
Oh and the failure on CI is to edit `ci/publish.rs` to add this new crate.

**Comment by peter-jerry-ye** [comment]
@alexcrichton Thank you for your review. I feel that the current version is ready for let's say, an experimental support for MoonBit. There may be potential bugs or further requests from users, but I may handle them in the future iterations.

**Review by alexcrichton — APPROVED** [review]
Sounds good, thanks again for your work on this!

Also I remember now, to clarify are you ok being the owner for the MoonBit integration? If we're unable to reach you and there's CI problems then MoonBit in CI might be disabled until you're able to come fix it. Is that ok with you?

**Comment by peter-jerry-ye** [comment]
Sure, that's ok

**Pull request merged**
