### PR TITLE
rust: export funcs explicitly invoke static constructors at most once

### PR DESCRIPTION
**Pull request by pchickey**
Before executing any other code, use this function (provided by wasm-ld)
to run all static constructors. When wasm-ld sees this explicit invocation
of ctors, it will not generate a wrapper aorund each exported func which
executes ctors first, and therefore we make sure that cabi_realloc doesnt
invoke ctors when called as an export func.
See https://github.com/bytecodealliance/preview2-prototyping/issues/99
for more details.

### CODE REVIEW

**Comment by pchickey** [comment]
https://github.com/bytecodealliance/preview2-prototyping/pull/101 demonstrates that this is a fix that prevents running constructors which call import functions from cabi_realloc

**Review by alexcrichton — APPROVED** [review]

**Comment by alexcrichton** [comment]
Hm actually is this correct in the face of multiple invocations? IIRC wasi-libc has no guards against repeatedly invoking this so this may run the risk of allocating the whole environment on each export call?

Should this instead be moved to `crates/guest-rust/src/lib.rs` and have a static bool guarding it so it's only invoked once?

**Comment by sunfishcode** [comment]
This is calling `__wasm_call_ctors` which is synthesized by wasm-ld, and it does not have guards against being called twice.

**Comment by pchickey** [comment]
Right, the present situation is that the ctors get called at the start of every export func, and this PR backs them that to all export funcs except cabi_realloc. Right now the ctors that exist in wasi-libc are tolerant of that behavior.

In the Rust bindgen, we can add a once cell to the guest-rust crate and make sure ctors get invoked only once.

In the C bindgen, its much more difficult to add that logic, since there is no global singleton (like a crate static can provide) to make sure constructors only get invoked once. So, I'm actually considering dropping this patch from the C bindgen, rather than provide a fix that would be somehow incorrect, and leaving it as a problem for tool conventions and the canonical abi to fix.

**Comment by pchickey** [comment]
Constructors run at most once, I rebased the C code generator changes out, and I added a note that this is just a temporary fix until rust 1.69.0 stabilizes, at which point wasi-libc ctors should no longer call import funcs (right?)

**Review by alexcrichton — APPROVED** [review]

**Comment by alexcrichton** [comment]
Oh the Windows failure reminds me, could the contents of the whole fuction added here be wrapped in `#[cfg(target_arch = "wasm32")]`? Technically it's only safe on single-threaded platforms like wasm anyway and shouldn't do anything anywhere else otherwise.

**Comment by pchickey** [comment]
Yes the target arch guard got dropped, by accident, in my refactor. I added it back in as a guard around the presence of the rt::run_ctors_once function.

**Pull request merged**
