### PR TITLE
feature(c#): Adds enum lifting and lowering

### PR DESCRIPTION
**Pull request by jsturtevant**
Adds support for enums in c#.  It also adds a simple code-gen test for enums which makes it easy to validate.

### CODE REVIEW

**Comment by jsturtevant** [comment]
Do we need to protect against invalid integer values for the enums or is that covered via the parser/abi?

**Comment by yowl** [comment]
https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#despecialization

I don't know if I undestand this correctly but it seems enums can be `None` ?

**Comment by alexcrichton** [comment]
You should be able to rely on all the values here being trusted and valid in a purist sense. It's not possible to call an API with a nonexistent enum discriminant with a standards-conformant runtime. If C# has an equivalent for debug assertions I'd recommend debug asserting that the discriminant is in bounds, but otherwise you're good to assume it's always valid.

(I think I'm answering the question here but I'm also not 100% sure what you mean by `None` handling)

**Comment by yowl** [comment]
Basically I was reading that link and here 

image


I saw "None", and wasn't sure what it meant.

**Comment by alexcrichton** [comment]
Ah that "None" means there's no type payload, so the canonical ABI of `enum foo { a, b }` is the same as `variant foo { a, b }` (since the `a` and `b` cases of `variant foo` have no payload)

**Comment by jsturtevant** [comment]
> @jsturtevant do you want to add the `Debug.Assert` for `Enum.IsDefined` maybe or leave it as a TODO?

I rebased on top of options work and added debug statement

**Comment by jsturtevant** [comment]
Thanks for the clarification on both points @alexcrichton

**Review by yowl — APPROVED** [review]
Thanks!

**Pull request merged**
