### PR TITLE
Fix with bug and add test

### PR DESCRIPTION
**Pull request by fibonacci1729**
Supersedes https://github.com/bytecodealliance/wit-bindgen/pull/709

cc @rvolosatovs

### CODE REVIEW

**Review by rvolosatovs — APPROVED** [review]
LGTM - tested locally, thanks @fibonacci1729!

**Comment by alexcrichton** [comment]
Thanks!

**Comment by rvolosatovs** [comment]
@alexcrichton any chance we could get a patch release with this change published?

**Comment by alexcrichton** [comment]
Sure, I'll do that in https://github.com/bytecodealliance/wit-bindgen/pull/716

**Pull request merged**
