### PR TITLE
Update string representation to not `char*`

### LINKED ISSUE #662: C string bindings generate char*, change to uint8_t*
`wit-bindgen c ` generates a `struct` to deal with strings. However the suggestion is that the structure are going to be UTF8, most c developers would assume that a `char*` pointer would point to an ASCII string, they are likely to use c's `strlen`  or `strcmp`, etc, family of functions on these pointers, but of course these won't work. 

To avoid c developer confusion, can we change this to generate uint8_t* types ?

Original:
````
typedef struct {
  char*ptr;
  size_t len;
} greeter_string_t;
````

Desired:
````
typedef struct {
  uint8_t*ptr;
  size_t len;
} greeter_string_t;
````

### PR DESCRIPTION
**Pull request by alexcrichton**
Use `uint8_t*` to represent that it's not a normal `char*` since it's neither nul-terminated and it may also contain interior nul characters.

Closes #662

### CODE REVIEW

**Comment by alexcrichton** [comment]
@Mossaka would you be able to assist with the Go failures here? I could add some exceptions to ignore the tests but that seems infeasible in this case because it'd break all usage of strings from Go

**Comment by Mossaka** [comment]
Yup I'll take a look at today. Thanks for letting me know

**Comment by alexcrichton** [comment]
Thanks! Not super urgent, but there may also be a simple fix too

**Comment by Mossaka** [comment]
@alexcrichton I just added a commit, should fix the Go failures.

**Review by Mossaka — APPROVED** [review]

**Pull request merged**
