### PR TITLE
Bump the wasi-sdk to 22.0

### PR DESCRIPTION
**Pull request by jsturtevant**
This updates to the latest version and also works towards removing EMSDK for the c# generator (https://github.com/dotnet/runtimelab/pull/2592)

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]

**Review by dicej — APPROVED** [review]
Looks like the Windows CI job is still running as I type this.  I'll be interested to see if we need to change anything in the NuGet or csproj config to get the latest build of the NativeAOT-LLVM packages or if that will just happen automatically.

**Comment by yowl** [comment]
> just happen automatically.

Should do, we use `9.0.0-*` so until .net 9 goes out (when we will go to 10) we should be fine.

**Comment by dicej** [comment]
Oops, I just realized: we should use `wasi-sdk-22.0.m-mingw64.tar.gz` instead of `wasi-sdk-22.0.m-mingw.tar.gz`, since that will help us avoid https://github.com/WebAssembly/wasi-sdk/issues/326

**Comment by jsturtevant** [comment]
> Oops, I just realized: we should use wasi-sdk-22.0.m-mingw64.tar.gz instead of wasi-sdk-22.0.m-mingw.tar.gz, since that will help us avoid https://github.com/WebAssembly/wasi-sdk/issues/326Oops, I just realized: we should use wasi-sdk-22.0.m-mingw64.tar.gz instead of wasi-sdk-22.0.m-mingw.tar.gz, since that will help us avoid https://github.com/WebAssembly/wasi-sdk/issues/326

I can address that in a followup.  I was going to open up a PR to use clang instead of emscripten for https://github.com/bytecodealliance/wit-bindgen/blob/2645c4f7ddefa0844a91b214267b1674e45d4884/crates/csharp/src/csproj.rs#L114-L119

**Comment by dicej** [comment]
This is what I did locally for testing, FWIW:
```diff
                 <Target Name="CheckWasmSdks">
-                    <Error Text="Emscripten not found, not compiling to WebAssembly. To enable WebAssembly compilation, install Emscripten and ensure the EMSDK environment variable points to the directory containing upstream/emscripten/emcc.bat"
-                        Condition="'$(EMSDK)' == ''" />
+                    <Error Text="Wasi SDK not found, not compiling to WebAssembly. To enable WebAssembly compilation, install Wasi SDK and ensure the WASI_SDK_PATH environment variable points to the directory containing share/wasi-sysroot"
+                           Condition="'$(WASI_SDK_PATH)' == ''" />
+                    <Warning Text="The WASI SDK version is too low. Please use WASI SDK 22 or newer with a 64 bit Clang."
+                             Condition="!Exists('$(WASI_SDK_PATH)/VERSION')" />
                 </Target>
                 "#,
             );
@@ -115,7 +117,7 @@ impl CSProjectLLVMBuilder {
                 Inputs=\"$(MSBuildProjectDirectory)/{camel}_cabi_realloc.c\"
                 Outputs=\"$(MSBuildProjectDirectory)/{camel}_cabi_realloc.o\"
                 >
-                <Exec Command=\"emcc.bat &quot;$(MSBuildProjectDirectory)/{camel}_cabi_realloc.c&quot; -c -o &quot;$(MSBuildProjectDirectory)/{camel}_cabi_realloc.o&quot;\"/>
+                <Exec Command=\"&quot;$(WASI_SDK_PATH)/bin/clang&quot; --target=wasm32-wasi &quot;$(MSBuildProjectDirectory)/{camel}_cabi_realloc.c&quot; -c -o &quot;$(MSBuildProjectDirectory)/{camel}_cabi_realloc.o&quot;\"/>
               </Target>
             "
             ));
```

**Pull request merged**
