### PR TITLE
test(c#): Add smoke runtime test

### PR DESCRIPTION
**Pull request by jsturtevant**

### CODE REVIEW

**Comment by jsturtevant** [comment]
The module is in a recursive loop.  From what I can tell it appears to be because the import and export have the same name and `*` is used in `dllimport`.  I am guessing that it is picking our dll instead of the imported?  

https://github.com/bytecodealliance/wit-bindgen/blob/d40ab04c5eed6e916b547a0eac70e4ac0c67e0cb/crates/csharp/src/lib.rs#L667C6-L676

**Comment by yowl** [comment]
RIght, this problem will be fixed when the new WasmImportLinkage attribute is implemented in the compiler.  I'm doing that at the moment, but some other RyuJit changes are slowing me up.

**Comment by jsturtevant** [comment]
Makes sense now, missed that it was for this! Thanks!

**Comment by yowl** [comment]
Thanks, the merge is in with the new attribute.  I will try to get the PR for the compiler in this evening.

**Comment by jsturtevant** [comment]
https://github.com/dotnet/runtimelab/pull/2444

**Comment by jsturtevant** [comment]
This should work after #791

**Comment by jsturtevant** [comment]
I've rebased but error looks related to something about pulling the correct packages:

```
C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\8.0.100\NuGet.targets(156,5): error : Failed to download package 'runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM.9.0.0-alpha.1.23619.1' from 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/fe324174-469a-4296-a9cb-1fd885bb6f2b/nuget/v3/flat2/runtime.win-x64.microsoft.dotnet.ilcompiler.llvm/9.0.0-alpha.1.23619.1/runtime.win-x64.microsoft.dotnet.ilcompiler.llvm.9.0.0-alpha.1.23619.1.nupkg'. [D:\a\wit-bindgen\wit-bindgen\target\runtime-tests\strings\csharp-strings\Strings.csproj]
```

@yowl any ideas?

**Comment by yowl** [comment]
Seems like it is invalid for some reason:

ERROR 403: Time-Limited URL validation failed

**Comment by yowl** [comment]
I think there must be some maintenance or something going on, try in 30 minutes, the link from https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-experimental/NuGet/runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM/overview/9.0.0-alpha.1.23619.1 is not working.

**Comment by jsturtevant** [comment]
thanks, I reproduced this locally but it does seem temporary. Will try again later in the day

**Comment by jsturtevant** [comment]
Alright does seem like it was a flake.  Test is passing now 🚀

**Review by yowl — APPROVED** [review]
LGTM!

**Pull request merged**
