### PR TITLE
Update wasm-tools crates

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Review by pchickey — APPROVED** [review]

**Comment by alexcrichton** [comment]
cc @Mossaka I had to [ignore the "flavorful" runtime test](https://github.com/bytecodealliance/wit-bindgen/pull/1005/files#diff-47fe2a08c5d84ec082f9c6c8d2a00126c85bfd4d6cd8a1ddca69b9e2fab765b4R270) for TinyGo because I think it might be surfacing a preexisting issue from before this PR (I could be wrong though)

**Comment by Mossaka** [comment]
> I had to [ignore the "flavorful" runtime test](https://github.com/bytecodealliance/wit-bindgen/pull/1005/files#diff-47fe2a08c5d84ec082f9c6c8d2a00126c85bfd4d6cd8a1ddca69b9e2fab765b4R270) for TinyGo

Cool I want to create an issue to track that. Do you have the error message (CI build link)?

**Comment by Mossaka** [comment]
> I had to [ignore the "flavorful" runtime test](https://github.com/bytecodealliance/wit-bindgen/pull/1005/files#diff-47fe2a08c5d84ec082f9c6c8d2a00126c85bfd4d6cd8a1ddca69b9e2fab765b4R270) for TinyGo

Cool I want to create an issue to track that. Do you have the error message (CI build link)?

**Comment by alexcrichton** [comment]
Ah sorry no CI link, it's from a local build. Removing the exemption in the line I highlighted I get:

```
failures:

---- flavorful::run stdout ----
dir: /home/alex/code/wit-bindgen/target/runtime-tests/flavorful/go-flavorful
status: exit status: 1
stdout: ------------------------------------------

stderr: ------------------------------------------
# wit_flavorful_go/gen
gen/flavorful.go:672:20: cannot use lower_result_f0 (variable of type C.struct_exports_test_flavorful_test_list_typedef2_t) as C.struct_test_flavorful_test_list_typedef2_t value in assignment
gen/flavorful.go:692:20: cannot use lower_result_f1 (variable of type C.struct_exports_test_flavorful_test_list_typedef3_t) as C.struct_test_flavorful_test_list_typedef3_t value in assignment

thread 'flavorful::run' panicked at tests/runtime/main.rs:317:13:
failed to compile
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    flavorful::run
```

**Pull request merged**
