### PR TITLE
Implement case-insensitive kebab-case comparison

### PR DESCRIPTION
**Pull request by sunfishcode**
Implement case-insensitive comparisons for kebab-case names as described in the component-model thread:

https://github.com/WebAssembly/component-model/issues/118

This also adds previously missing validation for duplicate names in some contexts.

### CODE REVIEW

**Comment by sunfishcode** [comment]
This doesn't yet implement case-insensitive comparisons for wit-component's decoder, though that could be added using the same `KebabNamespace` utility introduced here.

**Review by alexcrichton — APPROVED** [review]

**Comment by alexcrichton** [comment]
Would you be ok retargeting this at the `wasm-tools` repository? 

Additionally for the changes to `decoding.rs` in wit-component, would it be ok to leave those out for now? Eventually these changes need to make their way into `wasmparser`'s validation where after that it shouldn't be necessary to have the changes in `decoding.rs`, and for now it seems unlikely a bug will crop up due to that.

**Comment by peterhuene** [comment]
Just an FYI, but I also have a PR nearly ready for `wasm-tools` that brings the tooling up to date with kebab case validation in `wasmparser`

**Comment by sunfishcode** [comment]
@peterhuene Cool, I'll wait for your changes then. Closing this PR as the code is no longer in this repo.

**Pull request closed without merging**
