### PR TITLE
Testing tweaks to the csharp-mono project generation

### PR DESCRIPTION
**Pull request by lewing**
This is just an initial pass to become familiar with the tests and start reducing the differences between the csharp targets

### CODE REVIEW

**Review by jsturtevant — APPROVED** [review]
LGTM

**Comment by jsturtevant** [comment]
@lewing anything else needed on this?

**Comment by jsturtevant** [comment]
We are bumping into the known issue with the return pointer alignment.  I will disable that test until we can track down the issue.  fyi @yowl

**Comment by yowl** [comment]
I have a fix incoming, which at least solves the variant problem

**Comment by yowl** [comment]
> I have a fix incoming, which at least solves the variant problem

https://github.com/bytecodealliance/wit-bindgen/pull/945

**Pull request merged**
