### PR TITLE
feat(go): add a TinyGo guest generator (WIP, do not merge!)

### PR DESCRIPTION
**Pull request by Mossaka**
I started this work as a hackathon project. It currently can only work with integer functions for both import/export. It's not nearly half done yet, but I want to put this out to those who are interested in. Any feedback on the go user application's experience would be much welcomed!

This is also a place to track things to be done:
- [x] type numbers
- [x] update to use the world generator trait
- [x] type record
- [x] type flags
- [x] type tuple
- [x] type string
- [ ] type varient
- [ ] type option
- [ ] type union
- [ ] type enum
- [ ] type alias
- [x] type list
- [ ] type builtin
- [ ] "go:generate" and executable that hides "init" function
- [ ] ~type resource~

Signed-off-by: Jiaxiao Zhou <jiazho@microsoft.com>

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
curious. is this intended to be go like normal go? (GOOS=js) or tinygo js or tinygo wasi?

**Comment by Mossaka** [comment]
@codefromthecrypt 

This is intended to be tinygo wasi.

**Comment by Mossaka** [comment]
I am working on update this "ancient" PR to the newest component model world generator. Then I will implement the remaining types.

**Comment by Mossaka** [comment]
Closing this outdated draft PR as I am working on a new branch to bring tinygo guest binding generator.

**Pull request closed without merging**
