### PR TITLE
Reorganize folder structure

### PR DESCRIPTION
**Pull request by Kylebrown9**
Implements #244

Folders are now organized in a consistent way that makes it clear which crates are generators and whether each generator is host/guest. Renames crates to match the new folder names and updates the associated usages and feature flags.

### CODE REVIEW

**Comment by Kylebrown9** [comment]
This is ready for review, except the `README.md` changes, which I'm still working on.

**Comment by alexcrichton** [comment]
This all seems reasonable enough to me but I think it would be good to get some other eyes on this as well. @peterhuene you're likely interested in this since you've been working a lot with the rust-to-component stuff recently. Additionally @sunfishcode or @kulakowski-wasm y'all may also be interested in weighing in on the particulars here.

**Comment by sunfishcode** [comment]
The new naming here makes sense to me!

**Comment by Kylebrown9** [comment]
Ready on my end.

I'd recommend keeping "releases" / version bumps separate from feature impl PRs.
So if we want to bump to `0.3.0` after this, which I think would be a good idea, I'll make a new PR after.

**Comment by sunfishcode** [comment]
Sounds like there are no strong objections, so let's merge this, and iterate from here if there are any follow-up concerns.

**Pull request merged**
