### PR TITLE
full qualify Address to avoid collision with wit record of same name

### PR DESCRIPTION
**Pull request by nick1udwig**
In trying to compile Java to a WASM component, I ran into trouble because [my wit file](https://github.com/kinode-dao/kinode-wit/blob/master/kinode.wit#L25-L28) defines a `record address`. This collides with the codegen which frequently uses [teavm Address](https://github.com/konsoletyper/teavm/blob/master/interop/core/src/main/java/org/teavm/interop/Address.java)es.

This PR changes the codegen to fully qualify all Addresses, avoiding collision with user-defined `Address` classes.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Mind adding a test in `tests/codegen/*.wit` for this too?

**Review by alexcrichton — APPROVED** [review]

**Comment by nick1udwig** [comment]
Hmm, looks like the windows tests failed. Is this a "re-run and it'll work" scenario or should I take a second look at my test wit file?

**Comment by alexcrichton** [comment]
I think this is a retry situation, although I already retried once and it failed that time too... In any case I don't believe this is related to this PR so I'll try to take it from here

**Comment by alexcrichton** [comment]
It appears this is less flaky than expected, I've pinged @dicej who might be able to help here a bit more on Monday with this.

**Comment by dicej** [comment]
The "return pointer not aligned" issue was intended to be addressed in https://github.com/bytecodealliance/wit-bindgen/commit/bcd136e583c51cb6819876478bdfd6bf96e1ea2d, but it looks like there's still a problem.  I've pinged Scott to see what he thinks, and I'll try to debug it myself as well.

**Comment by dicej** [comment]
I'm able to reproduce it locally; will try to debug.  If I don't make progress, we'll just need to disable the C# `variants` runtime test for the time being.

**Comment by dicej** [comment]
The generated code appears to be correct AFAICT (e.g. using `ulong` for 64-bit alignment), so maybe something's off at a lower level. For the time being, I'm disabling that test: https://github.com/bytecodealliance/wit-bindgen/pull/963

**Pull request merged**
