### PR TITLE
fix(TS): use `/**` doc string in TS 

### PR DESCRIPTION
**Pull request by willemneal**
This way the comments will be proper TS doc strings and show up in hover overs, etc.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think this may need some custom handling to handle alignment in the source which might be good to implement, right now I suspect it generates:

```
/*
*
*
*/
```

where I suspect what we should instead generate is:

```
/*
 *
 *
 */
```

Otherwise seems reasonable though!

**Comment by alexcrichton** [comment]
To confirm, does this look ok in generated code to you? I forget if appended code is automatically trimmed or not...

**Comment by willemneal** [comment]
@alexcrichton It's trimmed.  Since it's a generated file and the comment does still show up, it's probably not a big deal.

Also in my other project I'm looking at using some JS prettier on the output.  So I think we could save properly formatted code for later.

**Comment by alexcrichton** [comment]
Ok seems reasonable to go with this and we can fix formatting later if necessary.

**Pull request merged**
